### ISSUE TITLE
IMGUI files not found when building game_controller sample

### ISSUE THREAD

**Issue by markvideon** [android/games-samples#68]
Two issues here. 

- The first: `common` and `third_party` are siblings in the file structure, but CMakeLists.txt do not currently reflect this. The setting of IMGUI_BASE_DIR looks for `third_party` one level deeper than it should. 
- The IMGUI files are simply not present in the third_party folder. On the surface, [this repo](https://github.com/ocornut/imgui/tree/master) appears to fit what is expected.

**Comment by natetrost** [comment]
The directory hierarchy for the game controller sample was altered in this PR https://github.com/android/games-samples/pull/57 Are you running from the head? The mismatch may be due to an older pull/incomplete update.

Imgui needs to be cloned separately, the installation instructions are in the game controller sample README.

**Comment by markvideon** [comment]
Yep, all sorted now. Thanks!
